### ISSUE TITLE
get filename from webdav url

### ISSUE THREAD

**Issue by MartijnRas** [Offerel/firefox_davmarks#2]
Currently the filename is hardcoded on line 1 in background.js:

  const filename = "bookmarks.json";

I think the user should be able to pick the name, and it should be part of the 'WebDAV URL' in the options.

As a side effect this will also make it possible to host multiple bookmarks files on the same webdav share, for instance one for private bookmarks and one for professional bookmarks.

**Comment by Offerel** [comment]
Yes, this is intended, because this AddOn serves primarily as a companion to the Roundcube plugin. In Roundcube each user is assigned his own bookmark file. This avoids misunderstandings.
